volumes:
  postgres_data:
  redis_data:
  src:
  media:
  static:
  logs:

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - logs:/logs
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

#  web:
#    build: .
#    command: >
#      bash -c " python3  manage.py migrate && python manage.py runserver 0.0.0.0:8001"
#    restart: unless-stopped
#    env_file:
#      - .env
#    volumes:
#      - .:/src
#      - ./media:/src/mediafiles
#      - ./static:/src/static
#      - logs:/logs
#    ports:
#      - "8001:8001"
#    depends_on:
#      - redis
#      - db

  redis:
    restart: unless-stopped
    image: redis:alpine
    command: redis-server --requirepass OMeDuTERnUtH
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data