# Generated by Django 5.1.7 on 2025-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submission',
            table='submissions',
        ),
    ]
